//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radiology_Center.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string note { get; set; }
        public Nullable<int> accountant_id { get; set; }
    
        public virtual accountant accountant { get; set; }
    }
}
